name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  format:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 20
          uses: actions/setup-java@v3
          with:
            java-version: '20'
            distribution: 'corretto'
        - uses: axel-op/googlejavaformat-action@v3
