name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'corretto'

    - name: Download Google Java Format Release
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "google/google-java-format"
        tag: "v1.18.1"
        fileName: "google-java-format-1.18.1-all-deps.jar"

    - name: Autoformat with Google Java Format
      run: "java -jar ./google-java-format-1.18.1-all-deps.jar --replace $(git ls-files *.java)"

    - name: Commit Autoformatted Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: auto format all java files"
